---
# Path to the user's XDG configuration directory (typically ~/.config)
xdg_config_dir: "{{ ansible_facts['user_dir'] }}/.config"

# Path to the user's local data directory (typically ~/.local/share)
xdg_data_dir: "{{ ansible_facts['user_dir'] }}/.local/share"
