# To Install: Set state to present.
# To Uninstall: Set state to absent.

---
sys_packages:
  # Fonts
  # - { name: "jetbrains-mono-fonts", state: "present" }
  # - { name: "fira-code-fonts", state: "present" }

  # CLI Tools
  - { name: "fastfetch", state: "present" }
  - { name: "tree", state: "present" }
  - { name: "unzip", state: "present" }
  - { name: "unrar", state: "present" }
  - { name: "wget", state: "present" }
  - { name: "zip", state: "present" }
  - { name: "fish", state: "present" }
  - { name: "neovim", state: "present" }
  - { name: "ripgrep", state: "present" }
  - { name: "fd-find", state: "present" }
  - { name: "wl-clipboard", state: "present" }
  - { name: "asciinema", state: "present" }
  - { name: "starship", state: "present" }
  - { name: "zellij", state: "present" }

  # GUI Apps
  - { name: "kdenlive", state: "present" }
  - { name: "steam", state: "present" }
  - { name: "converseen", state: "present" }
  - { name: "calibre", state: "present" }

  # Dev / SDK
  - { name: "ansible", state: "present" }
  - { name: "git", state: "present" }
  - { name: "nodejs", state: "present" }
  - { name: "clang", state: "present" }
  - { name: "pkgconf", state: "present" }
  - { name: "python3", state: "present" }
  - { name: "python3-pip", state: "present" }
  - { name: "mesa-utils", state: "present" }
  - { name: "golang", state: "present" }
  - { name: "delve", state: "present" }
  - { name: "java-latest-openjdk-devel", state: "present" }
  - { name: "android-tools", state: "present" }
  - { name: "gtk3-devel", state: "present" }
  - { name: "hugo", state: "present" }

enabled_services:
  - { name: "keyd", state: "started", enabled: yes }
